//
// Created by Congyu Luo on 7/18/23.
//

#ifndef CJ_2_COMMON_H
#define CJ_2_COMMON_H

#define STRING_TABLE_INIT_SIZE 8

#define OBJECT_ATTR_TABLE_INIT_SIZE 8
#define CLASS_ATTR_TABLE_INIT_SIZE 8

#define CHUNK_INIT_SIZE 16
#define OBJ_ARRAY_INIT_SIZE 8

#define MAX_CLASS_NUM 256

#define EXECUTE_CHUNK

//#define TIME_EXECUTION

//#define PRINT_CLASS_AFTER_INIT

// Runtime DS

#define RUNTIME_LIST_INIT_SIZE 8
#define RUNTIME_DICT_INIT_SIZE 8
#define RUNTIME_SET_INIT_SIZE 8

// VM
#define GLOBAL_REF_TABLE_INIT_SIZE 8
#define LOCAL_REF_TABLE_INIT_SIZE 8
#define VM_STACK_INIT_SIZE 256
#define VM_LOCAL_REF_TABLE_STACK_INIT_SIZE 128

// Compiler
#define IDENTIFIER_BUFFER_SIZE 32
#define CONTINUE_JUMP_LIST_INIT_SIZE 32
#define BREAK_JUMP_LIST_INIT_SIZE 32
#define INCLUDE_STACK_SIZE 32
#define MAX_SOURCE_SIZE 128
#define OPTIMIZE_CONST_PAYLOAD

//#define DEBUG_PRINT_VM_STACK
//#define DEBUG_PRINT_TOKENS
//#define DEBUG_PRINT_PRIOR_TO_OPTIMIZATION
//#define DEBUG_PRINT_CHUNK_AFTER_CREATION
//#define DEBUG_PRINT_CHUNK_AFTER_GLOBAL_OPTIMIZATION
//#define DEBUG_PRINT_LOCAL_REF_TABLE
//#define DEBUG_PRINT_PRELINKED_FUNC_LIST

// Constant List
#define CONST_BLOCK_SIZE 32

// Runtime Memory Management
#define RUNTIME_BLOCK_SIZE 64
#define FREE_STACK_SIZE 128
//#define PRINT_MEMORY_INFO

// Error Tracing
#define PRINT_ERROR_OP

// GC
//#define PRINT_GC_INFO
//#define PRINT_GC_REMOVAL

#endif //CJ_2_COMMON_H
